update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.176 2018/02/08 11:51:19 fulford Exp fulford $
+## $Id: archive,v 1.177 2018/02/08 12:03:48 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.176 $
+# $Revision: 1.177 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.176 2018/02/08 11:51:19 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.177 2018/02/08 12:03:48 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 dbtmp=/tmp/$cmd-db$$
 mysqldump=/usr/bin/mysqldump
@@ -79,101 +79,19 @@ sed -ne '/^merlin:$/,/^$/{
 }' <$config >$xtmp
 [ $verbose ] && cat $xtmp
 
-
 # Add -v to rsync opts if in verbose mode
 if [ $verbose ];then
 	rs_opts="$rs_opts -v"
 fi
-exit #yell
 # Get databases to archive
 sed -ne '/^'$host_id':/,/^$/p' $config|
 	awk -F: '/^[ \t]db:/{print $2}' >$dbtmp
 ftphost=${ftphost:-$host}
 [ $host != `hostname -f` ] && { remote="ssh -y $host";bs="bs=8192" ;}
 
-_end () {
-	if [ "$r" -eq 0 ];then
-		[ "$log" ] && logger -t archive: "$cmd on $host finished"
-		[ "$verbose" ] && echo "$cmd on $host finished `date`" >&2
-	else
-		[ "$log" ] && logger -t archive: "$cmd on $host failed"
-		echo "$cmd on $host failed" >&2
-		cat $tmp
-		[ -f $dbtmp ] && cat $dbtmp
-		
-	fi
-	rm $tmp
-	[ -f $dbtmp ] && rm $dbtmp
-
-}
-
-# backup databases if true
-[ $db -eq 0 ] && {
-	cat $dbtmp|
-	while read line;do
-		pass=`echo $line|awk -F= '{printf $2}'`
-		if [ $pass ] ;then 
-			user=$db
-			pass="-p$pass"
-		else
-			user=root
-			pass=""
-		fi
-		archive=$dest/$db.`date +%u`.sql
-		db=`echo $line|awk -F'=' '{printf $1}'`
-		[ "$verbose" ] &&{
-		     echo "sudo $mysqldump -h $host -u $user $pass --databases $db|">&2
-		     echo "dd $status of=$archive">&2
-		}
-		[ $log ] && logger -t $cmd "sqldump of $db as $user started"
-		sudo $mysqldump -h $host -u $user $pass $db|sudo dd $status of=$archive
-		r=$?
-		[ $llog ] && {
-			if [ $r -eq 0 ] ;then
-			 	result=completed
-			else
-				result=failed
-			fi
-			logger -t $cmd "sqldump of $db as $user failed"
-		}
-	done
-}
-
-# do rsync if true).
-[ $rs -eq 0 ] &&{
-	# check for rsync
-	if [ -n "$rs_opts" ] ;then
-		# Add excludes to variable rs_xclude
-		xclude=`awk <$xtmp '{printf("--exclude %s",$1)}'`
-
-		# Add excludes to rsync opts
-		rs_opts="$rs_opts $xclude"
-
-		[ "$root_usr" = y ] && {
-			sudo="sudo"
-		}
-		[ $verbose ] && {
-			echo "$cmd: starting $rsync $rs_opts $rsrc $rest:" >&2
-		}
-		[ $log ] && {
-			echo logger -t $cmd  "starting $rsync $rs_opts  on $host" 
-		}
-		if $remote sudo $sync $rs_opts $rsrc $rdest;then
-			echo complete
-		else
-			 echo failed
-		fi
-		[ $verbose ] && {
-			echo "$cmd: rsync on $host $result" >&2
-		} 
-		[ $log ] && {
-			logger -t $cmd "rsync on $host $result"
-		}
-	fi
-}
-
+# Functions
 #backup files if true 
-if [ $files -eq 0 ] ; tnen
+_backup_files () {
 	method=`echo $backup|awk '{print $1}'`
 
 	[ -z "$backup" ] &&{
@@ -185,10 +103,11 @@ if [ $files -eq 0 ] ; tnen
 	sudo [ -e "$dest" ] ||{
 		echo "$cmd: $dest does not exist">&2;exit 1
 	}
-
+echo yell;exit 
 	if sudo [ ! -w $dest ];then
 		echo "$backup: Can't write to $dest">&2 ;_end
   	fi
+echo yell;exit #yell
 	if [ $method == "tar" ];then 
   	 	if [ -n "$fss" ] ;then
 			$remote df -l|
@@ -263,5 +182,96 @@ if [ $files -eq 0 ] ; tnen
 			echo $result >&2
 		}
 	fi
+}
+
+# Finish off
+_end () {
+	if [ "$r" -eq 0 ];then
+		[ "$log" ] && logger -t archive: "$cmd on $host finished"
+		[ "$verbose" ] && echo "$cmd on $host finished `date`" >&2
+	else
+		[ "$log" ] && logger -t archive: "$cmd on $host failed"
+		echo "$cmd on $host failed" >&2
+		cat $tmp
+		[ -f $dbtmp ] && cat $dbtmp
+		
+	fi
+	rm $tmp
+	[ -f $dbtmp ] && rm $dbtmp
+
+}
+
+
+# backup databases if true
+[ $db -eq 0 ] && {
+	cat $dbtmp|
+	while read line;do
+		pass=`echo $line|awk -F= '{printf $2}'`
+		if [ $pass ] ;then 
+			user=$db
+			pass="-p$pass"
+		else
+			user=root
+			pass=""
+		fi
+		archive=$dest/$db.`date +%u`.sql
+		db=`echo $line|awk -F'=' '{printf $1}'`
+		[ "$verbose" ] &&{
+		     echo "sudo $mysqldump -h $host -u $user $pass --databases $db|">&2
+		     echo "dd $status of=$archive">&2
+		}
+		[ $log ] && logger -t $cmd "sqldump of $db as $user started"
+		sudo $mysqldump -h $host -u $user $pass $db|sudo dd $status of=$archive
+		r=$?
+		[ $llog ] && {
+			if [ $r -eq 0 ] ;then
+			 	result=completed
+			else
+				result=failed
+			fi
+			logger -t $cmd "sqldump of $db as $user failed"
+		}
+	done
+}
+
+# do rsync if true).
+[ $rs -eq 0 ] &&{
+	# check for rsync
+	if [ -n "$rs_opts" ] ;then
+		# Add excludes to variable rs_xclude
+		xclude=`awk <$xtmp '{printf("--exclude %s",$1)}'`
+
+		# Add excludes to rsync opts
+		rs_opts="$rs_opts $xclude"
+
+		[ "$root_usr" = y ] && {
+			sudo="sudo"
+		}
+		[ $verbose ] && {
+			echo "$cmd: starting $rsync $rs_opts $rsrc $rest:" >&2
+		}
+		[ $log ] && {
+			echo logger -t $cmd  "starting $rsync $rs_opts  on $host" 
+		}
+		if $remote sudo $sync $rs_opts $rsrc $rdest;then
+			echo complete
+		else
+			 echo failed
+		fi
+		[ $verbose ] && {
+			echo "$cmd: rsync on $host $result" >&2
+		} 
+		[ $log ] && {
+			logger -t $cmd "rsync on $host $result"
+		}
+	fi
+}
+
+#backup files if true 
+if [ $files -eq 0 ] ;tnen
+	[ $verbose ] &&{
+		echo "$cmd: Backing up file systems">&2
+	}
+	_backup_files()
 fi
 _end
