update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.186 2018/07/07 11:20:17 fulford Exp fulford $
+## $Id: archive,v 1.187 2018/07/07 11:24:43 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.186 $
+# $Revision: 1.187 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.186 2018/07/07 11:20:17 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.187 2018/07/07 11:24:43 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 dbtmp=/tmp/$cmd-db$$
 mysqldump=/usr/bin/mysqldump
@@ -64,6 +64,30 @@ else
 	exit 1
 fi
 
+# Finish off
+_end () {
+	r=$1
+	if [ "$r" -eq 0 ];then
+		[ "$log" ] &&{
+		   logger -t archive "$cmd of $host from `hostname` finished"
+		}
+		[ "$verbose" ] && {
+		   echo "$cmd of $host from `hostname` finished `date`">&2
+		}
+	else
+		[ "$log" ] && {
+		    logger -t archive: "$cmd on $host from `hostname` failed"
+		}
+		echo "$cmd on $host from `hostname` failed" >&2
+		cat $tmp
+		[ -f $dbtmp ] && cat $dbtmp
+		
+	fi
+	rm $tmp
+	[ -f $dbtmp ] && rm $dbtmp
+
+}
+
 # Extract config for host_id
 sed -ne '/^'$host_id':/,/^$/{
 	/^[	 ]db:.*/d 
@@ -98,33 +122,7 @@ ftphost=${ftphost:-$host}
 [ $host != `hostname -f` ] && { remote="ssh -y $host";bs="bs=8192" ;}
 
 # Functions
-#backup files if true 
-# function temporaril in file
-
-# Finish off
-_end () {
-	r=$1
-	if [ "$r" -eq 0 ];then
-		[ "$log" ] &&{
-		   logger -t archive "$cmd of $host from `hostname` finished"
-		}
-		[ "$verbose" ] && {
-		   echo "$cmd of $host from `hostname` finished `date`">&2
-		}
-	else
-		[ "$log" ] && {
-		    logger -t archive: "$cmd on $host from `hostname` failed"
-		}
-		echo "$cmd on $host from `hostname` failed" >&2
-		cat $tmp
-		[ -f $dbtmp ] && cat $dbtmp
-		
-	fi
-	rm $tmp
-	[ -f $dbtmp ] && rm $dbtmp
-
-}
-
+# backup files if true 
 
 # backup databases if true
 [ $db -eq 0 ] && {
