update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.166 2018/02/08 11:14:55 fulford Exp fulford $
+## $Id: archive,v 1.167 2018/02/08 11:20:14 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.166 $
+# $Revision: 1.167 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.166 2018/02/08 11:14:55 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.167 2018/02/08 11:20:14 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 dbtmp=/tmp/$cmd-db$$
 mysqldump=/usr/bin/mysqldump
@@ -107,15 +107,6 @@ _end () {
 
 }
 
-[ -z "$dest" ] &&{ echo "$cmd: no tape device specified for $host">&2;exit 1;}
-sudo [ -e "$dest" ] ||{ echo "$cmd: $dest does not exist">&2;exit 1;}
-[ -z "$backup" ] &&{
-	echo "$cmd: no backup command specified for $host">&2;exit 1
-}
-
-if sudo [ ! -w $dest ];then
-	echo "$backup: Can't write to $dest">&2 ;_end
-fi
 # backup databases if true
 [ $db -eq 0 ] && {
 	cat $dbtmp|
@@ -184,6 +175,16 @@ fi
 #backup files if true 
 [ $files -eq 0 ] &&{
   method=`echo $backup|awk '{print $1}'`
+
+  [ -z "$backup" ] &&{
+	echo "$cmd: no backup command specified for $host">&2;exit 1
+  }
+  [ -z "$dest" ] &&{ echo "$cmd: no tape device specified for $host">&2;exit 1;}
+	sudo [ -e "$dest" ] ||{ echo "$cmd: $dest does not exist">&2;exit 1;}
+
+  if sudo [ ! -w $dest ];then
+	echo "$backup: Can't write to $dest">&2 ;_end
+  fi
   case $method in	
   	tar) if [ -n "$fss" ] ;then
 		$remote df -l|
