update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.171 2018/02/08 11:26:55 fulford Exp fulford $
+## $Id: archive,v 1.172 2018/02/08 11:45:10 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.171 $
+# $Revision: 1.172 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.171 2018/02/08 11:26:55 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.172 2018/02/08 11:45:10 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 dbtmp=/tmp/$cmd-db$$
 mysqldump=/usr/bin/mysqldump
@@ -173,77 +173,79 @@ _end () {
 }
 
 #backup files if true 
-if [ $files -ne 0 ] ; tnen
-	[ $verbose ] && {
-		 echo "$cmd: File backup not required" >&2
+if [ $files -eq 0 ] ; tnen
+	method=`echo $backup|awk '{print $1}'`
+
+	[ -z "$backup" ] &&{
+		echo "$cmd: no backup command specified for $host">&2;exit 1
 	}
-else 
-  method=`echo $backup|awk '{print $1}'`
+	[ -z "$dest" ] &&{
+		echo "$cmd: no tape device specified for $host">&2;exit 1
+	}
+	sudo [ -e "$dest" ] ||{
+		echo "$cmd: $dest does not exist">&2;exit 1
+	}
 
-  [ -z "$backup" ] &&{
-	echo "$cmd: no backup command specified for $host">&2;exit 1
-  }
-  [ -z "$dest" ] &&{ echo "$cmd: no tape device specified for $host">&2;exit 1;}
-	sudo [ -e "$dest" ] ||{ echo "$cmd: $dest does not exist">&2;exit 1;}
-
-  if sudo [ ! -w $dest ];then
-	echo "$backup: Can't write to $dest">&2 ;_end
-  fi
-  case $method in	
-  	tar) if [ -n "$fss" ] ;then
-		$remote df -l|
-		awk 'NR > 1{
-		 if($1 !~ /tmpfs/ && $1 !~ /loop/ && $1 !~ /sr0/)print $6}'>$tmp
-		n=`cat $tmp|wc -l` 
-		c=0
-		while [ $c -le $n ];do
-			c=`expr $c + 1`
-			fss="$fss `awk <$tmp -v c=$c 'NR == c{print}'`"
-		done
-		# Get excludes
-		xcld=`awk <$xtmp '{printf("--exclude=%s ",$1)}'`
-	      fi
-	      for fs in $fss ;do
-	   	fn=`basename $fs`
-		[ $fn = "/" ] && fn=root
-		archive=`date +%u`.${fn}.tar
-		[ "$zip" ] && archive=${archive}.gz
-		[ $verbose ] && {
-			echo -n "$cmd: file system $fn on $host to $archive: ">&2
-		}
-		[ $log ] && {
-			logger -t $cmd "file system $fn on $host to $archive: started"
-		}
-		[ "$mode" = "test" ] &&{ echo="echo -n" ;}
-		if [ -n "$remote" ];then 
-			$remote "sudo $backup $xcld - $fs 2>/dev/null|gzip -c|
-			dd $status bs=8192" |
-			sudo dd $status of=$dest/$archive
-		else
-			if [ "$zip" = "y" ];then 
-				sudo $backup - $fs 2>/dev/null|sudo gzip|
-				sudo dd $status of=$dest/$archive 2>/dev/null
-				r=$?
+	if sudo [ ! -w $dest ];then
+		echo "$backup: Can't write to $dest">&2 ;_end
+  	fi
+	if [ $method == "tar ];then 
+  	 	if [ -n "$fss" ] ;then
+			$remote df -l|
+			awk 'NR > 1{
+		 		if($1 !~ /tmpfs/ && $1 !~ /loop/ && $1 !~ /sr0/)print $6
+			}'>$tmp
+			n=`cat $tmp|wc -l` 
+			c=0
+			while [ $c -le $n ];do
+				c=`expr $c + 1`
+				fss="$fss `awk <$tmp -v c=$c 'NR == c{print}'`"
+			done
+			# Get excludes
+			xcld=`awk <$xtmp '{printf("--exclude=%s ",$1)}'`
+	        fi
+		for fs in $fss ;do
+	   		fn=`basename $fs`
+			[ $fn = "/" ] && fn=root
+			archive=`date +%u`.${fn}.tar
+			[ "$zip" ] && archive=${archive}.gz
+			[ $verbose ] && {
+				echo -n "$cmd: file system $fn on $host to $archive: ">&2
+			}
+			[ $log ] && {
+				logger -t $cmd "file system $fn on $host to $archive: started"
+			}
+			[ "$mode" = "test" ] &&{ echo="echo -n" ;}
+			if [ -n "$remote" ];then 
+				$remote "sudo $backup $xcld - $fs 2>/dev/null|
+				gzip -c|
+				dd $status bs=8192" |
+				sudo dd $status of=$dest/$archive
 			else
-				sudo $backup - $fs 2>/dev/null|
-				sudo dd $status of=$dest/$archive 2>/dev/null
-				r=$?
-			fi
-		 fi
+				if [ "$zip" = "y" ];then 
+					sudo $backup - $fs 2>/dev/null|
+					sudo gzip|
+					sudo dd $status of=$dest/$archive 2>/dev/null
+					r=$?
+				else
+					sudo $backup - $fs 2>/dev/null|
+					sudo dd $status of=$dest/$archive 2>/dev/null
+					r=$?
+				fi
+		 	fi
 	            	if [ $r -eq 0 ]; then
 				result="complete"
 		    	else 
 				result="failed"
 		    	fi
 		    	[ "$log" ] && {
-			logger -t $cmd: "$fn on $host to $archive - $result."
+				logger -t $cmd: "$fn on $host to $archive - $result."
 		    	}
 		    	[ $verbose ] && {
 				echo $result >&2
 		    	}
-		done
-		;;
-	 lftp)
+	done
+	if [ $method == "lftp" );then
 		[ $verbose ] && {
 		    echo -n "$cmd using $backup to mirror $host to $dest: " >&2
 		}
@@ -261,6 +263,6 @@ else
 			echo $result >&2
 		}
 		;;
-	esac
+	fi
 fi
 _end
