update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.168 2018/02/08 11:23:50 fulford Exp fulford $
+## $Id: archive,v 1.169 2018/02/08 11:24:36 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.168 $
+# $Revision: 1.169 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.168 2018/02/08 11:23:50 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.169 2018/02/08 11:24:36 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 dbtmp=/tmp/$cmd-db$$
 mysqldump=/usr/bin/mysqldump
@@ -174,7 +174,7 @@ _end () {
 
 #backup files if true 
 if [ $files -ne 0 ];tnen
-	[ $verbose ] && {echo "$cmd: File backup not required" >&2 ;}
+	[ $verbose ] && { echo "$cmd: File backup not required" >&2 }
 else 
   method=`echo $backup|awk '{print $1}'`
 
