update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.152 2018/02/06 19:44:34 fulford Exp $
+## $Id: archive,v 1.153 2018/02/06 19:55:25 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.152 $
+# $Revision: 1.153 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.152 2018/02/06 19:44:34 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.153 2018/02/06 19:55:25 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 mysqldump=/usr/bin/mysqldump
 db=0
@@ -54,20 +54,24 @@ if [ -r $config ];then
 		echo "$cmd: $host_id not found in $config">&2
 		exit 1
 	}
+	# Extract config for host
 	sed -ne '/^'$host_id':/,/^$/{
 		/^[	 ]db:.*/d 
 		/*[	 ]exclude:.*/d 
 		/^[	 ].*/p
 	}' $config >$tmp
-	. $tmp
-	exclude=`sed -ne '/^merlin:$/,/^$/{
-	                s/[      ]*exclude:\(.*\)$/--exclude \1/p
-		}' <$config|
-        	awk '{x=" "$0" "x}END{print x}'
-	`
-	rs_opts="$rs_opts $exclude"
 	[ $verbose ] && cat $tmp
-	
+	# Set config
+	. $tmp
+	# Get excludes for host
+	sed -ne '/^merlin:$/,/^$/{
+	          s/[      ]*exclude:\(.*\)$/--exclude \1/p
+	}' <$config|
+        awk '{x=" "$0" "x}END{print x}' > $tmp 
+	[ $verbose ] && cat $tmp
+	# Add excludes to rsync opts
+	rs_opts="$rs_opts $(<$tmp)"
+	# Get databases to archive
 	sed -ne '/^'$host_id':/,/^$/p' $config|
 		awk -F: '/^[ \t]db:/{print $2}' >$dbtmp
 else
@@ -134,7 +138,7 @@ fi
 	done
 }
 
-# do rsync true).
+# do rsync if true).
 [ $rs -eq 0 ] &&{
 	# check for rsync
 	if [ -n "$rsync" ] ;then
@@ -147,6 +151,8 @@ fi
 		[ $log ] && {
 			echo logger -t $cmd  "starting rsync on $host" 
 		}
+		echo $remote "$sudo rsync $rs_opts $rsrc $rdest && echo complete || echo failed"
+		exit
 		result=`$remote "$sudo rsync $rs_opts $rsrc $rdest && echo complete || echo failed"`
 		[ $verbose ] && {
 			echo "$cmd: rsync on $host $result" >&2
