update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,15 +1,15 @@
 #!/bin/bash
-# $Id: archive,v 1.67 2016/02/15 17:48:14 fulford Exp fulford $
+# $Id: archive,v 1.68 2016/02/16 18:08:44 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.67 $
+# $Revision: 1.68 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
 # For assistance contact fulford@fulford.net 0709 229 5385
 ###################################################################
 cmd=`basename $0`
-syntax="$cmd [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_name>|-V"
-ver=`echo "$Id: archive,v 1.67 2016/02/15 17:48:14 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+syntax="$cmd [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
+ver=`echo "$Id: archive,v 1.68 2016/02/16 18:08:44 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 while [ $# -gt 0 ] ;do
 	case $1 in 
 		-c) config=$2;shift 2;;
@@ -19,25 +19,36 @@ while [ $# -gt 0 ] ;do
 		-v) verbose=1;shift;;
 		-V) echo "$cmd $ver";exit;;
 		-z) zip=y;shift;;
-		 *) host=$1;shift ;;
+		 *) host_id=$1;shift ;;
 	esac
 done
 config=${config:-"/usr/local/etc/archive.cf"}
-[ -z "$host" ]&&{ echo "$cmd: host name required" >&2 ;exit 1 ;}
-[ $host != `hostname` ] && { remote="ssh $host";bs="bs=8192" ;}
+[ -z "$host_id" ]&&{ echo "$cmd: host_id required" >&2 ;exit 1 ;}
 tmp=/tmp/$cmd-$$
+dbtmp=/tmp/$cmd-db$$
 verbose=${verbose:-0}
-[ "$log" ] && logger -t archive: "$cmd on $host started"
+[ "$log" ] && logger -t archive: "$cmd on $host_id started"
 if [ -r $config ];then
-	sed -ne '/^'$host':/,/^$/{
-		/^[	 ].*/,/^$/p
+	sed -ne '/^'$host_id':/,/^$/{
+		/^[	 ]db:.*/d 
+		/^[	 ].*/p
 	}' $config >$tmp
 	. $tmp
 	[ $verbose -eq 1 ] && cat $tmp
+	sed -ne '/^'$host_id':/,/^$/p' $config|
+		awk -F: '/^[ \t]db:/{print $2}' >$dbtmp
 else
 	echo "$cmd: Can't read $config" >&2
 	exit 1
 fi
+cat $dbtmp|
+while read line;do
+	db=`echo $line|awk -F= '{print $1}'
+	pass=`echo $line|awk -F= '{print $2}'
+	mysqldump -u root@$host -p $pass
+done
+exit
+[ $host != `hostname` ] && { remote="ssh $host";bs="bs=8192" ;}
 
 _end () {
 	if [ $r -lt 1 ];then
@@ -99,4 +110,10 @@ case $method in
 	;;
 
 esac
+cat $dbtmp|
+while read line;do
+	db=`echo $line|awk -F= '{print $1}'
+	pass=`echo $line|awk -F= '{print $2}'
+	mysqldump -u root@$host -p $pass
+done
 _end
