update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.187 2018/07/07 11:24:43 fulford Exp fulford $
+## $Id: archive,v 1.188 2018/07/07 11:26:50 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.187 $
+# $Revision: 1.188 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[[-f]|[-r]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.187 2018/07/07 11:24:43 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.188 2018/07/07 11:26:50 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 dbtmp=/tmp/$cmd-db$$
 mysqldump=/usr/bin/mysqldump
@@ -52,17 +52,6 @@ start=`date`
 [ "$log" ] && logger -t archive: "$cmd of $host_id started"
 [ "$verbose" ] && echo "$cmd on $host_id started $start" >&2
 
-# Check if configuration available
-if [ -r $config ];then
-	grep -q "^$host_id:$" $config ||{
-		echo "$cmd: $host_id not found in $config">&2
-		logger -t archive: "$host_id not found in $config."
-		_end 1
-	}
-else
-	echo "$cmd: Can't read $config" >&2
-	exit 1
-fi
 
 # Finish off
 _end () {
@@ -87,6 +76,18 @@ _end () {
 	[ -f $dbtmp ] && rm $dbtmp
 
 }
+
+# Check if configuration available
+if [ -r $config ];then
+	grep -q "^$host_id:$" $config ||{
+		echo "$cmd: $host_id not found in $config">&2
+		logger -t archive: "$host_id not found in $config."
+		_end 1
+	}
+else
+	echo "$cmd: Can't read $config" >&2
+	exit 1
+fi
 
 # Extract config for host_id
 sed -ne '/^'$host_id':/,/^$/{
