update

diff --git a/archive b/archive
--- a/archive
+++ b/archive
@@ -1,7 +1,7 @@
 #!/bin/bash
-## $Id: archive,v 1.99 2017/05/12 10:29:53 fulford Exp $
+## $Id: archive,v 1.100 2017/05/12 11:03:12 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/archive,v $
-# $Revision: 1.99 $
+# $Revision: 1.100 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford. 
 # Licensed for public use under the GPL.
@@ -9,7 +9,7 @@
 ###################################################################
 cmd=`basename $0`
 syntax="$cmd [[-b]|[-f]] [-c <config>] [-d(debug)] [-v(erbose)] [-z(ip)] <host_id>|-V"
-ver=`echo "$Id: archive,v 1.99 2017/05/12 10:29:53 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: archive,v 1.100 2017/05/12 11:03:12 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 r=0
 dbo=1
 fo=1
@@ -39,6 +39,10 @@ dbtmp=/tmp/$cmd-db$$
 verbose=${verbose:-0}
 [ "$log" ] && logger -t archive: "$cmd on $host_id started"
 if [ -r $config ];then
+	grep -s $host_id ||{
+		echo "$cmd: $host_id not found in $config">&2
+		exit 1
+	}
 	sed -ne '/^'$host_id':/,/^$/{
 		/^[	 ]db:.*/d 
 		/^[	 ].*/p
